# Introdução ao `numpy`

In [1]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos

Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [2]:
A = np.array([[2,0],[4,6],[8,2]])
B = np.array([[1,3],[5,7]])
v1 = np.array([5,3])
v2 = np.array([9,2,1])

In [3]:
print('Dimensão do A: ',A.shape)
print('Dimensão do B: ',B.shape)
print('Dimensão do v1: ',v1.shape)
print('Dimensão do v2: ',v1.shape)

Dimensão do A:  (3, 2)
Dimensão do B:  (2, 2)
Dimensão do v1:  (2,)
Dimensão do v2:  (2,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\mathbf{T}} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [4]:
print(A.T)

[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\mathtt{A[0]} &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\mathtt{A[[0,2]]} &= \begin{bmatrix}2 & 0\\ 8 & 2\\ 2 & 0\end{bmatrix}\\
\end{aligned}$$

In [6]:
print(A[0], A[0].shape) # Primeira linha de A
print(A[[0,2]], A[[0,2]].shape) # Primeira e terceira linha de A
print(A[[0]], A[[0]].shape) # Primeira linha de A

[2 0] (2,)
[[2 0]
 [8 2]] (2, 2)
[[2 0]] (1, 2)


$$\begin{aligned}
\mathtt{A[:,0]} &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\mathtt{A[:,[0]]} &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [5]:
print(A[:,0], A[:,0].shape) # Primeira coluna do A
print(A[:,[0,1]], A[:,[0,1]].shape) # Primeira e segunda coluna do A
print(A[:,[0]], A[:,[0]].shape) # Primeira coluna do A

[2 4 8] (3,)
[[2 0]
 [4 6]
 [8 2]] (3, 2)
[[2]
 [4]
 [8]] (3, 1)


## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [9]:
print(np.eye(5))
print(np.zeros((5,3)))
print(np.ones((3,1)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]
 [1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [10]:
print(np.random.rand(5,3))
print(np.random.randn(2,2))

[[0.18146144 0.70119289 0.49608692]
 [0.19133697 0.11113832 0.40920959]
 [0.99708905 0.50886431 0.01634342]
 [0.4069161  0.64266401 0.24719659]
 [0.72352739 0.09696198 0.46827778]]
[[-1.61160729  0.45737586]
 [-0.83392063 -0.41605848]]


## Operações lineares

In [ ]:
print(5 * A)

Ou seja...
$$\begin{aligned}
\mathtt{5 * A} = 5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [ ]:
print(A + A)

Ou seja...
$$\begin{aligned}
\mathtt{A + A} = \boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [ ]:
print(v1 * A)

$$\begin{aligned}
\mathtt{v1 * A} = \boldsymbol{v}_1 \odot \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\odot\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print(v1 + A)

$$\begin{aligned}
\mathtt{v1 + A} = \boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [11]:
try:
    v2 + A
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,) (3,2) 


In [12]:
try:
    A + B
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [13]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [14]:
print(np.sqrt(A))
print(A ** 0.5)

[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

In [ ]:
np.mean(A), np.sum(A), np.prod(A)

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [18]:
np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [20]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [21]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [22]:
A - np.mean(A, axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matriz

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. Em Python, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [ ]:
print(A @ B)
print('Dimensão de A @ B: ',(A@B).shape)

In [ ]:
try:
    B @ A
except Exception as e:
    print(e)

In [ ]:
print(A @ B @ v1)
print((A @ B) @ v1)

### Inversão de matriz
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [ ]:
print(B)

In [ ]:
B_inv = np.linalg.inv(B)
print(B_inv)

In [ ]:
print(B_inv @ B)

Também funciona com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [ ]:
print(B_inv @ v1)

Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$

In [ ]:
print(np.linalg.solve(B,v1))

In [ ]:
print(np.linalg.solve(B,B))

## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV, isso significa que o dado é estruturado da seguinte maneira:
```
idade, pressão_sanguínea # Um cabeçalho opcional
39, 144 # Dados separados por vírgulas ou outro separador
47, 220
....
```

In [ ]:
pressão_dataset = np.genfromtxt('./pressão.txt', delimiter=',', skip_header=1)
pressão_dataset

In [ ]:
peixe_dataset = np.genfromtxt('./peixe.txt', delimiter=',')
peixe_dataset

## Exercícios

### Computar a fórmula da normalização escore-Z

Dado um conjunto de dados $\boldsymbol{X} = [\boldsymbol{x}_0, \boldsymbol{x}_1, \ldots, \boldsymbol{x}_n]$, a normalização por escore-Z é dada por:
$$\boldsymbol{x_i} = \frac{\boldsymbol{x_i} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}$$

Onde:
$$\begin{aligned}
\boldsymbol{\mu} &= \frac{1}{n}\sum_i^n \boldsymbol{x_i}\\
\boldsymbol{\sigma} &= \sqrt{\frac{1}{n-1}\sum_i^n (\boldsymbol{x_i}-\boldsymbol{\mu})^2}\\
\end{aligned}$$

Use a fórmula para normalizar o conjunto de dados `peixe` sem usar nenhum `for` ou `while`.

In [ ]:
# Escrever aqui

### Encontrar raízes de funções

Dada uma função $f$, o seguinte procedimento consegue encontrar aproximar zeros desta função:

1. Inicialize $\tilde{x}_0$ com um chute inicial e escolha uma tolerância $\epsilon$;
2. Compute: $$\tilde{x}_{t} = \tilde{x}_{t-1} - \frac{f(\tilde{x}_{t-1})}{f'(\tilde{x}_{t-1})}$$
3. Repita o passo 2 até que $f(\tilde{x}_t) \leq \epsilon$.

Implemente esse procedimento para $f(x) = x^2 - 2$, teste seu resultado computando $\tilde{x} \cdot \tilde{x}$.

In [ ]:
# Escrever aqui

### Resolver uma regressão linear através de mínimos quadrados ordinários

Como visto na aula de regressão linear, dado o seguinte problema:
$$\begin{aligned}
\boldsymbol{X}\boldsymbol{W}^{\mathbf{T}} = \hat{\boldsymbol{y}}\\
\text{Queremos encontrar:}\\
\tilde{\boldsymbol{W}} = \arg\min_{\boldsymbol{W}} ||\boldsymbol{W}^{\mathbf{T}} \boldsymbol{X} - \boldsymbol{y}||^2
\end{aligned}$$

Como visto, sabemos que:
$$\tilde{\boldsymbol{W}} = (\boldsymbol{X}^{\mathbf{T}}\boldsymbol{X})^{-1} \boldsymbol{X}^{\mathbf{T}}\boldsymbol{y}$$

Encontre o $\tilde{\boldsymbol{W}}$ pro dataset `peixe` onde:
$$\boldsymbol{X} = \mathtt{peixe\_dataset[:,[1,2]}\\\boldsymbol{y} = \mathtt{peixe\_dataset[:,[0]]}$$

Sem utilizar estrutura de repetição alguma, calcule a raíz do erro quadrático médio:
$$\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_i^n (\boldsymbol{y} - \hat{\boldsymbol{y}})^2}$$

In [ ]:
# Escrever aqui